/*
 * (c) 2005 David B. Bracewell
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */

package com.gengoai.hermes.extraction;

import com.gengoai.collection.counter.Counter;
import com.gengoai.function.SerializableFunction;
import com.gengoai.hermes.HString;
import com.gengoai.hermes.ml.feature.ValueCalculator;
import lombok.NonNull;

import java.io.Serializable;
import java.util.List;

/**
 * <p>
 * An extraction is the output generated by an {@link Extractor}. Extractions provide access to HString and String
 * representations of the extracted content. Note that how the results are constructed are dependent on the extraction
 * technique. For example, some extractions only provide fragments (i.e. non-attached) HString due to the way extraction
 * is performed.
 * </p>
 *
 * @author David B. Bracewell
 */
public interface Extraction extends Serializable, Iterable<HString> {

   /**
    * Generates a Counter-based Extraction. Counter-based extractions do not have access to the original HString objects
    * and thus generate fragments when needed.
    *
    * @param counter the count of extractions represented as a Strings.
    * @return the Extraction
    */
   static Extraction fromCounter(@NonNull Counter<String> counter) {
      return new CounterExtraction(counter);
   }

   /**
    * Generates an HString-backed extraction with a provided function for converting the HString into string
    * representations. Methods on the extraction object resulting in Strings will first map the underlying extracted
    * HString using the provided <code>toString</code> method.
    *
    * @param list     the list of extracted HString
    * @param toString the function to use to map the extracted HString into String representations.
    * @return the Extraction
    */
   static Extraction fromHStringList(@NonNull List<HString> list,
                                     @NonNull SerializableFunction<HString, String> toString) {
      return new HStringExtraction(list, toString, null);
   }

   /**
    * Generates an HString-backed extraction with a provided function for converting the HString into string
    * representations. Methods on the extraction object resulting in Strings will first map the underlying extracted
    * HString using the provided <code>toString</code> method. When needed to generate a counter representation, the
    * provided ValueCalculator is used to transform the values.
    *
    * @param list       the list of extracted HString
    * @param toString   the function to use to map the extracted HString into String representations.
    * @param calculator the methodology for counting HString.
    * @return the Extraction
    */
   static Extraction fromHStringList(@NonNull List<HString> list,
                                     @NonNull SerializableFunction<HString, String> toString,
                                     ValueCalculator calculator) {
      return new HStringExtraction(list, toString, calculator);
   }

   /**
    * Generates an HString-backed extraction which will use the <code>HString.toString</code> for mapping to Strings and
    * will return raw counts for counter based methods.
    *
    * @param list the list of extracted HString
    * @return the Extraction
    */
   static Extraction fromHStringList(@NonNull List<HString> list) {
      return new HStringExtraction(list, HString::toString, null);
   }

   /**
    * Generates an String-backed extraction. String-based extractions do not have access to the original HString objects
    * and thus generate fragments when needed.
    *
    * @param list the list of extracted String
    * @return the Extraction
    */
   static Extraction fromStringList(@NonNull List<String> list) {
      return new StringExtraction(list, null);
   }

   /**
    * Generates an String-backed extraction. String-based extractions do not have access to the original HString objects
    * and thus generate fragments when needed. When needed to generate a counter representation, the provided
    * ValueCalculator is used to transform the values.
    *
    * @param list       the list of extracted String
    * @param calculator the methodology for counting String.
    * @return the Extraction
    */
   static Extraction fromStringList(@NonNull List<String> list, ValueCalculator calculator) {
      return new StringExtraction(list, calculator);
   }

   /**
    * Generates a count over string representations of the extractions
    *
    * @return the counter
    */
   Counter<String> count();

   /**
    * The number of items extracted
    *
    * @return the int
    */
   int size();

   /**
    * An iterable over the String representations of the extractions.
    *
    * @return the iterable
    */
   Iterable<String> string();

}//END OF Extraction
