#!/bin/bash

LANG=en
HERMES_RESOURCE_DIR=/data/hermes/
MODEL_FILE=$HERMES_RESOURCE_DIR/$LANG/models/phrase_chunk.model.bin
CORPUS_DIR=/data/corpora/

mode=`echo ${1:-"TRAIN"} | tr a-z A-Z`
jexec PhraseChunkTrainer --data "conll::$CORPUS_DIR/$LANG/phrase_chunk/train.txt" \
                     --model "$MODEL_FILE" --mode $mode --ndarray.factory SPARSE_FLOAT \
                     --com.gengoai.hermes.resources.dir "$HERMES_RESOURCE_DIR"
