#!/bin/bash

LANG=en
HERMES_RESOURCE_DIR=/data/hermes/
CORPUS_DIR=/data/corpora/hermes_data

function arguments() {
  case "$1" in
  POS)
    echo "--tagger EN_POS --df pos_opl::/$CORPUS_DIR/$LANG/part_of_speech/combined.txt --model $HERMES_RESOURCE_DIR/$LANG/models/pos.model.bin"
    ;;
  PHRASE_CHUNK)
    echo "--tagger PHRASE_CHUNK --df conll::$CORPUS_DIR/$LANG/phrase_chunk/combined.txt --model $HERMES_RESOURCE_DIR/$LANG/models/phrase_chunk.model.bin"
    ;;
  ENTITY)
    echo "--tagger ENTITY --df hjson_opl::$CORPUS_DIR/$LANG/named_entity/ontonotes_all_entities.json_opl --model $HERMES_RESOURCE_DIR/$LANG/models/ner.model.bin"
    ;;
  esac
}

model=$(echo $1 | tr a-z A-Z)

[ "$1" == "" ] && echo "Usage en_trainer [POS|PHRASE_CHUNK|ENTITY]"

args=$(arguments $model)
cd tools && jexec TaggerApp TRAIN $args "${@:2}"
