#!/bin/bash

LANG=en
HERMES_RESOURCE_DIR=/data/hermes/
MODEL_FILE=$HERMES_RESOURCE_DIR/$LANG/models/pos.model.bin
CORPUS_DIR=/data/corpora/


mode=$(echo "${1:-TRAIN}" | tr "[:lower:]" "[:upper:]")
jexec POSTrainer --corpus "$CORPUS_DIR/$LANG/part_of_speech/combined.txt" --format POS \
  --model "$MODEL_FILE" --mode $mode --ndarray.factory SPARSE \
  --com.gengoai.hermes.resources.dir "$HERMES_RESOURCE_DIR"
